//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Eye"",
            ""id"": ""2607b44d-6809-43c9-9faf-4c58dec8819b"",
            ""actions"": [
                {
                    ""name"": ""FaceButton_Down"",
                    ""type"": ""Button"",
                    ""id"": ""492a70d7-d509-4077-9b92-521c09c3ced8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FaceButton_Up"",
                    ""type"": ""Button"",
                    ""id"": ""4d094d4b-561f-46fc-98f1-bbb593f8f554"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FaceButton_Left"",
                    ""type"": ""Button"",
                    ""id"": ""6d342fe3-65d9-4c2b-92de-905a57cf613a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FaceButton_Right"",
                    ""type"": ""Button"",
                    ""id"": ""ab9255c7-60c8-4b01-b383-b96a40a289e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger_Left"",
                    ""type"": ""Value"",
                    ""id"": ""ba76a4a7-1887-4bd8-a686-715fe767a491"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger_Right"",
                    ""type"": ""Value"",
                    ""id"": ""ee61fb02-ee62-4494-916f-9543d9d53b30"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoulder_Left"",
                    ""type"": ""Value"",
                    ""id"": ""fa3c4ea9-661c-42d2-98e6-4abc1dd46137"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoulder_Right"",
                    ""type"": ""Value"",
                    ""id"": ""3198a317-7a22-4dba-b19f-e3a05f0f551c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4f096f5b-66b1-40b7-9602-d57986fba597"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceButton_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d834edb-b926-49c5-87fe-ff82c42cba51"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceButton_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b060b931-f1c0-4fb7-9c82-9846720b9365"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceButton_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89e4adad-13dd-404d-bdc2-02e58ee14ccb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceButton_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95d25fe8-9c43-4f0c-9df0-c4a448094b7f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91ad0187-aa74-4f42-a2a4-5de330faa617"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94f2f2b3-91ad-438a-8488-0dcb8a781a9f"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc9bf56b-7c33-43e6-95ac-02d0fba41e7f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Eye
        m_Eye = asset.FindActionMap("Eye", throwIfNotFound: true);
        m_Eye_FaceButton_Down = m_Eye.FindAction("FaceButton_Down", throwIfNotFound: true);
        m_Eye_FaceButton_Up = m_Eye.FindAction("FaceButton_Up", throwIfNotFound: true);
        m_Eye_FaceButton_Left = m_Eye.FindAction("FaceButton_Left", throwIfNotFound: true);
        m_Eye_FaceButton_Right = m_Eye.FindAction("FaceButton_Right", throwIfNotFound: true);
        m_Eye_Trigger_Left = m_Eye.FindAction("Trigger_Left", throwIfNotFound: true);
        m_Eye_Trigger_Right = m_Eye.FindAction("Trigger_Right", throwIfNotFound: true);
        m_Eye_Shoulder_Left = m_Eye.FindAction("Shoulder_Left", throwIfNotFound: true);
        m_Eye_Shoulder_Right = m_Eye.FindAction("Shoulder_Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Eye
    private readonly InputActionMap m_Eye;
    private IEyeActions m_EyeActionsCallbackInterface;
    private readonly InputAction m_Eye_FaceButton_Down;
    private readonly InputAction m_Eye_FaceButton_Up;
    private readonly InputAction m_Eye_FaceButton_Left;
    private readonly InputAction m_Eye_FaceButton_Right;
    private readonly InputAction m_Eye_Trigger_Left;
    private readonly InputAction m_Eye_Trigger_Right;
    private readonly InputAction m_Eye_Shoulder_Left;
    private readonly InputAction m_Eye_Shoulder_Right;
    public struct EyeActions
    {
        private @InputMaster m_Wrapper;
        public EyeActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @FaceButton_Down => m_Wrapper.m_Eye_FaceButton_Down;
        public InputAction @FaceButton_Up => m_Wrapper.m_Eye_FaceButton_Up;
        public InputAction @FaceButton_Left => m_Wrapper.m_Eye_FaceButton_Left;
        public InputAction @FaceButton_Right => m_Wrapper.m_Eye_FaceButton_Right;
        public InputAction @Trigger_Left => m_Wrapper.m_Eye_Trigger_Left;
        public InputAction @Trigger_Right => m_Wrapper.m_Eye_Trigger_Right;
        public InputAction @Shoulder_Left => m_Wrapper.m_Eye_Shoulder_Left;
        public InputAction @Shoulder_Right => m_Wrapper.m_Eye_Shoulder_Right;
        public InputActionMap Get() { return m_Wrapper.m_Eye; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EyeActions set) { return set.Get(); }
        public void SetCallbacks(IEyeActions instance)
        {
            if (m_Wrapper.m_EyeActionsCallbackInterface != null)
            {
                @FaceButton_Down.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Down;
                @FaceButton_Down.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Down;
                @FaceButton_Down.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Down;
                @FaceButton_Up.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Up;
                @FaceButton_Up.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Up;
                @FaceButton_Up.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Up;
                @FaceButton_Left.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Left;
                @FaceButton_Left.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Left;
                @FaceButton_Left.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Left;
                @FaceButton_Right.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Right;
                @FaceButton_Right.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Right;
                @FaceButton_Right.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnFaceButton_Right;
                @Trigger_Left.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnTrigger_Left;
                @Trigger_Left.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnTrigger_Left;
                @Trigger_Left.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnTrigger_Left;
                @Trigger_Right.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnTrigger_Right;
                @Trigger_Right.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnTrigger_Right;
                @Trigger_Right.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnTrigger_Right;
                @Shoulder_Left.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnShoulder_Left;
                @Shoulder_Left.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnShoulder_Left;
                @Shoulder_Left.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnShoulder_Left;
                @Shoulder_Right.started -= m_Wrapper.m_EyeActionsCallbackInterface.OnShoulder_Right;
                @Shoulder_Right.performed -= m_Wrapper.m_EyeActionsCallbackInterface.OnShoulder_Right;
                @Shoulder_Right.canceled -= m_Wrapper.m_EyeActionsCallbackInterface.OnShoulder_Right;
            }
            m_Wrapper.m_EyeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FaceButton_Down.started += instance.OnFaceButton_Down;
                @FaceButton_Down.performed += instance.OnFaceButton_Down;
                @FaceButton_Down.canceled += instance.OnFaceButton_Down;
                @FaceButton_Up.started += instance.OnFaceButton_Up;
                @FaceButton_Up.performed += instance.OnFaceButton_Up;
                @FaceButton_Up.canceled += instance.OnFaceButton_Up;
                @FaceButton_Left.started += instance.OnFaceButton_Left;
                @FaceButton_Left.performed += instance.OnFaceButton_Left;
                @FaceButton_Left.canceled += instance.OnFaceButton_Left;
                @FaceButton_Right.started += instance.OnFaceButton_Right;
                @FaceButton_Right.performed += instance.OnFaceButton_Right;
                @FaceButton_Right.canceled += instance.OnFaceButton_Right;
                @Trigger_Left.started += instance.OnTrigger_Left;
                @Trigger_Left.performed += instance.OnTrigger_Left;
                @Trigger_Left.canceled += instance.OnTrigger_Left;
                @Trigger_Right.started += instance.OnTrigger_Right;
                @Trigger_Right.performed += instance.OnTrigger_Right;
                @Trigger_Right.canceled += instance.OnTrigger_Right;
                @Shoulder_Left.started += instance.OnShoulder_Left;
                @Shoulder_Left.performed += instance.OnShoulder_Left;
                @Shoulder_Left.canceled += instance.OnShoulder_Left;
                @Shoulder_Right.started += instance.OnShoulder_Right;
                @Shoulder_Right.performed += instance.OnShoulder_Right;
                @Shoulder_Right.canceled += instance.OnShoulder_Right;
            }
        }
    }
    public EyeActions @Eye => new EyeActions(this);
    public interface IEyeActions
    {
        void OnFaceButton_Down(InputAction.CallbackContext context);
        void OnFaceButton_Up(InputAction.CallbackContext context);
        void OnFaceButton_Left(InputAction.CallbackContext context);
        void OnFaceButton_Right(InputAction.CallbackContext context);
        void OnTrigger_Left(InputAction.CallbackContext context);
        void OnTrigger_Right(InputAction.CallbackContext context);
        void OnShoulder_Left(InputAction.CallbackContext context);
        void OnShoulder_Right(InputAction.CallbackContext context);
    }
}
